version: '3.5'

services:
    eisen-server:
        build:
            context: ./server
        container_name: eisen-server
        ports:
            - 8500:8500

        networks: ["default", "nats"]

    nats:
        image: nats
        ports:
            - 8222:8222
            - 4222:4222
    
        networks: ["nats"]

    eisen-client:
        build:
            context: ./client
        container_name: eisen-client
        #stdin_open: true
        #tty: true

        networks: ["nats"]

networks:
    nats:
        name: nats



